### ISSUE TITLE
安装不成功！

### ISSUE THREAD

**Issue by micenote** [cangyan/macOS-10500-b460i#3]
i5-10600k
主板:和你的一样
没有独显。

安装ventura 启动的时候，自动重启，进不了安装界面。
![WechatIMG31](https://github.com/cangyan/macOS-10500-b460i/assets/13486634/20a14a71-ce9f-4ebf-9b8f-8feb34df2170)
到这一步就自动重启了。

**Comment by cangyan** [comment]
没有独显的话，可以试试前几个commit的。之前也是没有独显的
